### ISSUE TITLE
Figure a way to get the message ID

### ISSUE THREAD

**Issue by hdeshev** [wildbit/postmark-rails#1]
Postmark returns a message ID after it accepts an email that you can use when tracking delivery -- see if and when a message got sent, did it bounce, etc. We need a way to return that after calling 

Mail.delivery_something(...)

**Comment by morgler** [comment]
But how do I get the message ID in Rails, if I use ActionMailer and deliver_later?

**Comment by temochka** [comment]
@morgler, you should be able to use ActionMailer’s observers to access message ID when delivering messages in the background:

``` ruby
class PostmarkMailObserver
  def self.delivered_email(m)
    return unless m.delivered?
    puts ">>> Postmark Message-ID: #{m.message_id}"
  end
end

# Normally, you’d register an observer in an initializer
ActionMailer::Base.register_observer(PostmarkMailObserver)

AccountMailer.welcome_email(Account.first).deliver_later

### >>> Postmark Message-ID: 78b9cc7a-902a-40e0-b2c6-44f77521fea4
```

You can find out more about observers in [ActionMailer documentation](http://api.rubyonrails.org/v5.0/classes/ActionMailer/Base.html#method-c-register_observer).

I hope this helps.

**Comment by morgler** [comment]
Thanks, I will try that!

**Comment by cthornbe** [comment]
Did anyone ever figure this one out? I am able to register an observer but it doesn't have the message-id in the header either on a deliver_now or a deliver_later.

**Comment by temochka** [comment]
Hi @cthornbe! It’s not a header but an instance method on a `Mail::Message` instance (`#message_id`) which is defined by the gem. See the snippet above for an example.

**Comment by andreimoment** [comment]
@temochka, I am hoping to save the postmark message_id to the database and associate it with the record which sent the message in a Rails 6 app.

The messages are delivered like this:

```
UserMailer.password_reminder(@user, @reminder).deliver_now

where 

class UserMailer < ApplicationMailer
```

Where can I retrieve the ID?

**Comment by temochka** [comment]
@andreimoment this should work for `MessageID`:

```
message = UserMailer.password_reminder(@user, @reminder)
message.deliver_now
message_id = message.message_id
```

> Any way to retrieve this information from the UserMailer instance?

```
message.postmark_response
```

P.S. If this doesn’t help, I’d suggest emailing support@postmarkapp.com where some very smart (and, more importantly, up-to-date on the latest developments) folks can help you. I’m personally no longer with the company.

**Comment by andreimoment** [comment]
@temochka, thank you for your reply!

**Comment by nickpearson** [comment]
This behavior changed in the [postmark gem](https://github.com/wildbit/postmark-gem) v1.17.0 ([commit](https://github.com/wildbit/postmark-gem/commit/70583893a902d8d8febfb3b459e6b8540da11d3d#diff-535ab14eeac22b16349ee7505000ac94aa326f17f9a016d9fd25ead7ee7ad5af) and [changelog reference](https://github.com/wildbit/postmark-gem/blob/master/CHANGELOG.rdoc#label-1.17.0)).

Calling `message_id` on a sent `Mail::Message` now returns the locally generated mail ID rather than the Postmark message ID. To get the Postmark ID, you can use `message['X-PM-Message-Id'].to_s`.

There's a [postmark-gem issue](https://github.com/wildbit/postmark-gem/issues/100) about this, but I wanted to comment here because a search for `message_id` landed me on this issue and may do the same for others, as it seems to serve as the only documentation of this capability I could find.

**Comment by danlo** [comment]
Adding on to this ticket so that others who come across see the Rails 7.0.4 observer registration

Rails 7.0.4 guides  - https://guides.rubyonrails.org/action_mailer_basics.html#observing-emails

```ruby
class SandboxEmailInterceptor
  def self.delivering_email(message)
    message.to = ['sandbox@example.com']
  end
end

Rails.application.configure do
  if Rails.env.staging?
    config.action_mailer.interceptors = %w[SandboxEmailInterceptor]
  end
end
```

**Comment by shoaib-iqbal** [comment]
```
# config/initializers/mail_message_extension.rb
require 'mail'

module MailMessageExtension
  def deliver_and_track
    postmark_message_id = deliver['X-PM-Message-Id'].to_s
    Email.create(postmark_message_id: postmark_message_id)
  end
end

Mail::Message.send(:include, MailMessageExtension)


`
```
Later on you can call
`UserMailer.welcom_email.deliver_and_track`

**Comment by meceo** [comment]
> @andreimoment this should work for `MessageID`:
> 
> ```
> message = UserMailer.password_reminder(@user, @reminder)
> message.deliver_now
> message_id = message.message_id
> ```
> 
> > Any way to retrieve this information from the UserMailer instance?
> 
> ```
> message.postmark_response
> ```
> 
> P.S. If this doesn’t help, I’d suggest emailing [support@postmarkapp.com](mailto:support@postmarkapp.com) where some very smart (and, more importantly, up-to-date on the latest developments) folks can help you. I’m personally no longer with the company.

`mail.message_id` returns other value than `mail.postmark_response["MessageID"]`. The later works for me.

**Comment by andreimoment** [comment]
Thank you for your response!
