### ISSUE TITLE
How to we catch and handle Postmark::InvalidMessageError

### ISSUE THREAD

**Issue by noctivityinc** [wildbit/postmark-rails#19]
I noticed in my error log today a number of these:

```
Postmark::InvalidMessageError
You tried to send to a recipient that has been marked as inactive. Found inactive addresses:
```

Since we don't do anything special except use Rails 2.3's normal ActiveMailer for sending mail, how do we capture and act on these errors that the Gem is returning?

**Comment by ssurfr2819** [comment]
We would also be interested in handling these within a delayedjob configuration.

**Comment by noctivityinc** [comment]
Yeah that would be great.  That largest problem with the recommended solution is that DJ reports (via Airbrake or Exceptional or whatever) the DJ caught error, NOT the actual error that occurred.  This makes it extremely difficult to debug.

**Comment by zykadelic** [comment]
@temochka’s link seems to be old, this seems to be the new one: http://developer.postmarkapp.com/developer-api-bounce.html#activate-bounce

**Comment by bithavoc** [comment]
Found a way to catch these:
```
begin
  client.deliver(...)
catch => e
  if e.full_response['ErrorCode'] == 406
    // email address deactivated, ignore
  else 
    // important error happened
    raise
end
```

this is what `#full_response` usually contains:
```
{"ErrorCode"=>406, "Message"=>"You tried to send to a recipient that has been marked as inactive.\nFound inactive addresses: {redacted}.\nInactive recipients are ones that have generated a hard bounce or a spam complaint. "}
```

**Comment by chrispa** [comment]
This works fine for us....Rails 4.2 sending with a Postmark Template through Delayed Job.  You can just match the specific class of Postmark error you want to rescue.

```
begin
      postmark_client.deliver_with_template(
      ..........
      )
rescue Postmark::InvalidMessageError => error
     // mark as bounced or take other action...
end
```

**Comment by ndbroadbent** [comment]
Sorry to comment on such an old issue, but in my case these `Postmark::InvalidMessageError` exceptions started blowing up my Sentry error reports while I was testing [Rebound](https://postmarkapp.com/rebound) with an intentional hard bounce. I send my emails in a background job with Sidekiq, so it would keep retrying the job for the next few days if I didn't delete it manually.

To prevent this from happening in the future, I ignored the exception in my Raven configuration:

```
# config/initializers/_sentry.rb
Raven.configure do |config|
  config.excluded_exceptions << 'Postmark::InvalidMessageError'
end
```

Hope this helps someone else!
