### ISSUE TITLE
Different "from" name possible?

### ISSUE THREAD

**Issue by mech** [wildbit/postmark-rails#48]
Hi,

How do I override the "from name". For example in the Sender Signature, I may have specified:

`mech <mech@example.com>`

But somehow I want my name to reflect it as admin for a period of time like

`admin <mech@example.com>`

How can I do that without changing the Sender Signature?

**Comment by temochka** [comment]
In your Rails mailer, specify the desired To header value and that should do it:

``` ruby
class UserMailer < ActionMailer::Base
  default from: 'Default <default@example.com>'

  def welcome_email(user)
    @user = user
    mail to: user.email, from: 'Override <override@example.com>', subject: 'Welcome!', tag: 'welcome'    
  end
end
```

**Comment by mech** [comment]
Thanks :smile:
