### ISSUE TITLE
Documentation is wrong. :(

### ISSUE THREAD

**Issue by idyll** [wildbit/postmark-rails#56]
Should be `api_key` not `api_token` in the config example.

**Comment by temochka** [comment]
Hi @idyll,

Sorry about the trouble! There is no mistake though. Starting `v0.10.0`, the new (and recommended) configuration parameter name is `api_token` (to be consistent with the web app), so the README file uses the new name.

If you’re using an older version of the gem, it’ll only support the legacy `api_key` parameter name (the latest versions support both for backwards compatibility). This is why it’s always important to refer to the docs for your specific gem version. On GitHub, you can usually use the tag selector to view the README for your version of choice.

CHANGELOG: https://github.com/wildbit/postmark-rails/blob/master/CHANGELOG.rdoc#0100
0.9.x README: https://github.com/wildbit/postmark-rails/tree/v0.9.0
