### ISSUE TITLE
Add Rails5 gemfile to be tested against?

### ISSUE THREAD

**Issue by acorncom** [wildbit/postmark-rails#57]
As mentioned at https://github.com/wildbit/postmark-gem/issues/51#issuecomment-225233199, this gem isn't currently tested against Rails5.  Would it be possible to get that setup?

**Comment by acorncom** [comment]
For the record, with the little testing I've done of things so far this seems to be running fine with Rails 5.0.0 👍

**Comment by temochka** [comment]
Hi! Sorry, I forgot to update that older issue. There is no need to add another Gemfile. The default Gemfile always installs the latest stable version of the `actionmailer` gem as it is (and we don’t depend on full Rails gem). Custom gemfiles are only used for older versions of `actionmailer`. As specified in both the README and the [CHANGELOG for v0.13.0](https://github.com/wildbit/postmark-rails/blob/master/CHANGELOG.rdoc#0130), the gem is now verified to work with ActionMailer 5.0.

**Comment by acorncom** [comment]
Thanks!
