### ISSUE TITLE
HTTP Header not set

### ISSUE THREAD

**Issue by hungrymedia** [wildbit/postmark-rails#60]
I have followed the instructions for using this gem as a drop-in for ActionMailer, but am receiving the following error when attempting to trigger an email (Devise password reset). 

`Postmark::InvalidMessageError (No Account or Server API tokens were supplied in the HTTP headers. Please add a header for either X-Postmark-Server-Token or X-Postmark-Account-Token.)`

I would assume the following line would cause the API key to be passed through as the HTTP header:
`config.action_mailer.postmark_settings = { :api_token => Rails.application.secrets.postmark_api_token }`

But that does not appear to be the case.

I'm on Rails 5.0.4 and postmark-rails 0.15.0.

Thank you

**Comment by hungrymedia** [comment]
User error ;) closing

**Comment by etmartinkazoo** [comment]
I'm having the same issue; would you be able to shed any light on what was going wrong for you? Thanks.

**Comment by kaleazy** [comment]
Make sure to check `config/app.php` to add `postmark_secret`.

**Comment by temochka** [comment]
If anyone is having a similar problem, please double check that your [config/secrets.yml]() actually contains your server token (`postmark_api_token: xxxx-xxxx-xxxx`). If that doesn’t help, please email us at [mailto:support@postmarkapp.com](support@postmarkapp.com). We’re here to help :)

**Comment by rydan** [comment]
Same issue here. Even manually adding the X-Postmark-Server-Token header using the headers(<hash>) method right before calling mail() doesn't help...
