### ISSUE TITLE
apply_defaults error from ActionMailer

### ISSUE THREAD

**Issue by jsmestad** [wildbit/postmark-rails#62]
When trying to send an email using `TestMailer.mailer.deliver_now!` (following the guide during signup). The send renders the email fine, but errors inside ActionMailer on `apply_defaults` method.

Here is a link to the failure line in Rails 5.1.x - https://github.com/rails/rails/blob/5-1-stable/actionmailer/lib/action_mailer/base.rb#L894

Any idea what I am missing?

**Comment by temochka** [comment]
Hi @jsmestad,

Sorry, not sure what it could be. I might be able to give you more insight if you could share the source of your mailer action.
