### ISSUE TITLE
Can one use template ID instead of template alias? 

### ISSUE THREAD

**Issue by Slawikus** [wildbit/postmark-rails#68]
In the documentation templated mails it is mentioned that one can use alias to refer to particular template, but is there a way to use template ID?

**Comment by temochka** [comment]
Sorry, we don’t plan to support template IDs for the Rails integration. Our officially endorsed workflow looks something like this:

1. Create a Postmark server for each app environment (e.g., development, integration, staging, production)
2. Create/edit aliased templates in development.
3. [Push](https://postmarkapp.com/support/article/1069-how-do-i-copy-templates-to-another-server) changes up the deployment chain.

P.S. We plan to support Template IDs at the API level for the foreseeable future, but all new (e.g., template pushes) and upcoming template features will continue to require aliases. If you cannot switch to aliases for some reason, we’d love to learn about your use case. Drop us a line at [mailto:support@postmarkapp.com](support@postmarkapp.com): it’s a better medium for these conversations.
