### ISSUE TITLE
Document using the gem with Devise

### ISSUE THREAD

**Issue by temochka** [wildbit/postmark-rails#69]
The [Devise](https://github.com/plataformatec/devise) gem is the de-facto standard for implementing authentication in Rails. It also assumes the responsibility of sending some common types of transactional emails, such as sign up confirmations, password reset links, welcome emails, and others.

The postmark-rails gem is known to work seamlessly with Devise, as it relies on basic ActionMailer facilities. That said, some users reported confusion regarding how certain Postmark features (e.g., templates) fit with Devise. Thus, it might be worth providing an official guide for getting started with Devise on Postmark. Such guide would cover the following:

* Initial configuration
* Development VS production
* Customization (Rails templates VS Postmark templates)

**Comment by theAssholeDev** [comment]
any updates on this? Im implementing devise with postmark and would love some reference materials on this topic! i was reading the wiki but nothing stood out re: devise

**Comment by TheMindlessDevCanada** [comment]
@temochka I have just hooked up devise with a custom mailer using postmark Templates, I will send a PR with a wiki page perhaps it could be of assistance as i see this still seems to be a 'hot topic' I'll edit this with a gist i am going to do on this as well.

**Comment by temochka** [comment]
@TheMindlessDevCanada thank you for sharing this! I’m no longer with Postmark, but I wonder if @ibalosh or @tomazy could help.

**Comment by ibalosh** [comment]
@tomazy @nickhammond could you check out this one?

**Comment by tomazy** [comment]
Thank you @TheMindlessDevCanada! This is super helpful. We will incorporate this in our wiki as soon as possible.

**Comment by tomazy** [comment]
@TheMindlessDevCanada - we've added [a page](https://github.com/wildbit/postmark-rails/wiki/Using-Postmark-with-Devise-gem) to our wiki based on your work. Thanks again!
