### ISSUE TITLE
Rails 6.0

### ISSUE THREAD

**Issue by Medvezo** [wildbit/postmark-rails#70]
Hello!

It seems like you are not officially supporting Rails 6.0 (couldn't find any mention of it in the codebase + you don't test against it). Do you plan to offer 6.0 support? Do you think it will be safe to include this gem regardless?

Thanks! :wave:

**Comment by tomazy** [comment]
Hey @Medvezo we do plan to add support for Rails 6 soon, so you can safely use this gem.

**Comment by Dreamersoul** [comment]
Any update on rails 6 support?

**Comment by rdsoze** [comment]
Any update here?

**Comment by rianvdm** [comment]
Hey everyone, we're going to work on this and provide n update soon!

**Comment by pgraham3** [comment]
Hi everyone - we have tested the Rails gem with Rails 6 and updated the setup instructions for it in the README/Wiki. It is safe to use this gem with Rails 6 moving forward and it will be officially supported.

**Comment by Dreamersoul** [comment]
@pgraham3 thank you!
