### ISSUE TITLE
A 'TemplateModel' is required when using a template to send an email.

### ISSUE THREAD

**Issue by SimonHausdorf** [wildbit/postmark-rails#71]
I am getting this error for templates not using any template model

```
This message is using a Postmark template.

Alias: "password_change"
Model:
{
}

Use the #prerender method on this object to contact the Postmark API to pre-render the template.

Cheers,
Your friends at Postmark
Postmark::ApiInputError: A 'TemplateModel' is required when using a template to send an email.
```

**Comment by SimonHausdorf** [comment]
as a workaround

```
self.template_model = { tmp_fix: '' }
````

can be used

**Comment by nickhammond** [comment]
Hey @SimonHausdorf,

Sorry about that, I've updated the wiki article to mention that a template model should be specified.   A TemplateModel is a [required attribute](https://postmarkapp.com/developer/api/templates-api), here's a bit more information around our [template syntax](https://postmarkapp.com/support/article/1077-template-syntax) if you're curious.
