### ISSUE TITLE
Emoji encoding issues in subject lines with Rails 3/4 apps

### ISSUE THREAD

**Issue by pgraham3** [wildbit/postmark-rails#79]
If you use emoji in subject lines in a Rails 3 or 4 app, they will appear as rectangles in the resulting email:

![Screen Shot 2020-08-18 at 3 17 24 PM](https://user-images.githubusercontent.com/16660335/90571161-1432aa80-e166-11ea-8481-808419929e15.png)

Example mailer code to reproduce:

```
class UserMailer < ActionMailer::Base
  default from: 'sender@domain.com'

  def welcome
    mail(:subject => "😁Testing", :to => 'recipient@domain.com')
  end
end
```

Using latest version of rails gem (0.20.0).

**Comment by tomazy** [comment]
@pgraham3 I'm closing this issue hoping it got fixed by now. Feel free to reopen if you still experience it, or maybe create a PR with a fix ;-)
