### ISSUE TITLE
Recipient email format `"Recipient Name" <someone@example.com>` results in `Postmark::InvalidEmailAddressError`

### ISSUE THREAD

**Issue by brodyhoskins** [wildbit/postmark-rails#86]
I'm noticing an issue when using ActiveMailer to send emails with the following format in the `To:` header:

`"Recipient Name" <someone@example.com>`

Attempting to use this format results in:

`Postmark::InvalidEmailAddressError: Error parsing 'To': Illegal email address 'Recipient'. It must contain the '@' symbol.`

ActiveMailer typically allows us to do this, and we were doing so in order to use "pretty" recipient names in the email headers.

**Comment by tomazy** [comment]
@brodyhoskins sorry for late reply. I hope you've got it working. If not, please show us how you set this attribute in code and reopen this issue.
