### ISSUE TITLE
Delivery Options

### ISSUE THREAD

**Issue by muhammedtufekyapan** [wildbit/postmark-rails#87]
Hi everyone,

I'm using 'postmark-rails' gem on my application to send my transactional emails. Also, I use other platforms to send different emails for my other projects within the same app.

I use "delivery_options" to define SMTP information for each mailer. It works on localhost but doesn't work on Heroku. Any idea why this is happening?

**Comment by tomazy** [comment]
@muhammedtufekyapan sorry for late reply. I hope you got it working. If not, please provide more details on what kind of errors you're seeing and reopen the issue.
